language: python
python:
  - '2.7'
  - '3.2'
  - '3.3'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=1.6.5
install:
  - pip install -q coverage flake8 Django==$DJANGO
before_script:
  - psql -c 'CREATE DATABASE {{ project_name }};' -U postgres
script:
  - flake8 .
  - coverage run setup.py test
  - coverage report
