language: python
python:
  - '2.7'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=1.6.2
install:
  - pip install -q coverage flake8 Django==$DJANGO
before_script:
  - find . -name '*.py' -not -regex '.*/migrations/.*' -not -regex '.*/__init__.py' -exec flake8 --max-line-length=120 --max-complexity=10 '{}' \;
  - psql -c 'CREATE DATABASE {{ project_name }};' -U postgres
script:
  - coverage run --source='{{ project_name }}' --branch --omit='{{ project_name }}/migrations/*' setup.py test
  - coverage report --fail-under=100 --show-missing
